version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile-dev
    image: playnext:dev
    depends_on:
      - db
    networks:
      - client
    environment:
      NODE_ENV: development
    env_file: ./app/.env
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: npm run dev

  db:
    image: mongo:latest
    restart: always
    networks:
      client:
        aliases:
          - mongo
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27017:27017"

networks:
  client:
volumes:
  mongodbdata: