version: "3.8"
services:
  app:
    build: ./app
    image: app:dev
    networks:
      - client
    environment:
      NODE_ENV: development
    env_file: ./app/.env
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: npm run dev

networks:
  client: