version: "3.8"
services:
  app:
    build: ./app
    image: app:dev
    depends_on:
      - db
    networks:
      - client
    environment:
      NODE_ENV: development
    env_file: ./app/.env
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: npm run dev

  db:
    image: mongo:latest
    restart: always
    env_file: ./db/.env
    networks:
      client:
        aliases:
          - db
    volumes:
      - ./db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongodbdata:/data/db
    ports:
      - "27017:27017"

networks:
  client:
volumes:
  mongodbdata: